# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YTNewMedia_iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YTNewMedia_iOS

  target 'YTNewMedia_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'YYKit', '~> 1.0.9'
end
